language: c
sudo: false
env:
  global:
    - secure: "iWrZJIjEBSSwKPqwd6pxajhTmHss9CfB94sCCr4KxTreNrHd9X0exP5dSjiZzfmvUaMlFTLACFIWOHxcedjLNYgK4ZWQTj4qX/m9TUpOO2isN5K6ZbNJxzrTcJavU86MwxmT/XPFZKTPHrNQ0+711tT5zZ7cWEiV/QwRbrdYC438UjHQ781YIap2ko0bmp6tOMTrZjnm0dIB6ngMO2wYhxSel3LZ4vEhOgxZHKL3dXyynwIVmVtLMIJ9CHQ4Tj8lnbGnNc3VNCeoQB2YUe0kV0L6Jxlt9z3E3vKnYjT133oZnN+86I10C9+1MXuYni9XPvJ2FhEmUMiumSda2L5u+wE7r/esoGwUq59R7iEh/TPZmfREjHBRAvinS3OtfLifJs3WYkoa9qSfkk0V3d8hmqatlk+ngFPL3aN6UuAX5+dA0K5TxQ8RzIf16IoljZ7ruS3GocM5/7QYBvwrl8tRk7S0djEmuS5M4y8AHVnKzUVozDJFixQAjtW4Qx8XrLrv6h72dUyhcOw98IGWXbUKwhW3crSlkONgmi+lcf1fIzAJLvHksTpX7BHnN4+G7trgNo47qI0wBlhenEFLQYV4WwxOO01/eYClnm2XAV+s9CSyABYfxgf7LyagBq6jXWyqTLnF7Onte0jJkbv2LCRKOXR5xxJmEZTyBD/RwGWY3io="
matrix:
  include:
    - os: linux
      sudo: false
    - os: linux
      sudo: required
    - os: linux
      sudo: required
      dist: trusty
before_install:
  - ./install-icc.sh
  - source ~/.bashrc
script:
  - icc   -std=c99         test/test.c      -o test/testc
  - icpc  -std=c++11       test/test.cxx    -o test/testcxx
  - ifort -std08 -fpp      test/test.f90    -o test/testf90
  - icpc  -std=c++11  -tbb test/testtbb.cxx -o test/testtbbcxx
  - ifort -std08 -fpp -mkl test/testmkl.f90 -o test/testmklf90
notifications:
  email:
    on_success: change
    on_failure: change
