language: c
os:
  - linux

before_install:
  - ./install-icc.sh --components icc,openmp,ipp
script:
  - cat $HOME/.local/bin/icc
  - icc -o test/test test/test.c
notifications:
  email:
    on_success: change
    on_failure: change
