language: c
dist: trusty
sudo: required

before_install:
  - sudo ./install-icc.sh --components icc,openmp,ipp --dest /opt/intel
script:
  - source /opt/intel/bin/compilervars.sh intel64
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/ism/bin/intel64
  #- cat $HOME/.local/bin/icc
  - icc -o test/test test/test.c
notifications:
  email:
    on_success: change
    on_failure: change
